### ISSUE TITLE
Unable to resolve link target: RDMP.qmd

### ISSUE THREAD

**Issue by NeuroShepherd** [lmu-osc/FAIR-Data-Management#15]
https://github.com/lmu-osc/FAIR-Data-Management/blob/8dcaf96d5f99c559f0580f8529367a8d768f3464/documentation.qmd#L177

Hi @LeimLarissa, quick question: should this be a link to the `dmp.qmd` file rather than `RDMP.qmd`? The latter file does not exist.

**Comment by LeimLarissa** [comment]
Yes! It should be dmp.qmd.
